### ISSUE TITLE
Encrypted cores opened in `store.replicate()` have no access to encryptionKey

### ISSUE THREAD

**Issue by Nazeh** [hypercore-protocol/corestore-next#14]
At [store.replicate()](https://github.com/hypercore-protocol/corestore-next/blob/master/index.js#L253) cores are opened by their discoveryKey, but `encryptionKey` is not passed, nor is it saved in `userData`.

I tried to see if I can add it to `userData`, but didn't know how to override `core.encryptionKey` in `_preready()` since it is a [read-only](https://github.com/hypercore-protocol/hypercore-next/blob/ef01868c4715ed53ac57a37aa7eb91ffe26a9fd4/index.js#L415) property in Hypercore-next

**Comment by mafintosh** [comment]
Optional way would be to allow passing the encryption key to a session, as the core can easily function without it (ie blind replication)

**Comment by Nazeh** [comment]
this seems to do the trick in the `_preload()` :

```js
     if (existing.opened && !existing.closing) {
        if(opts.encryptionKey && !existing.encryptionKey) {
          await existing.close()
        }else {
          return { from: existing, keyPair, auth }
        }
      }
```

**Comment by Nazeh** [comment]
If that is acceptable solution I can open a PR

**Comment by Nazeh** [comment]
> Optional way would be to allow passing the encryption key to a session, as the core can easily function without it (ie blind replication)

I am only starting to familiarize myself with `core.session()` now, but so far it didn't work!

```js
/**
 * Open a core from the Corestore and ensure it has been initialized
 * with the right options, especially the encryption key.
 */
async function openCore(store, opts) {
  const core = await store.get(opts);
  await core.ready();
  const session = core.session(opts);
  await session.ready();
  console.log('session', session.encryptionKey);

  return session;
}
```

The code above logs `session null` unfortunately.

What am I doing wrong?

**Comment by Nazeh** [comment]
`core.session()` seems to override `core.auth` just fine, but not `encryptionKey`

**Comment by Nazeh** [comment]
I believe this is why `session()` is failing to open with the correct encryption: [`s._passCapabilities()`](https://github.com/hypercore-protocol/hypercore-next/blob/4cab710a75230314675b612d78ffb7e4d0f666de/index.js#L205)
