### ISSUE TITLE
shouldn't hypercore-crypto dependency be ^3.0.0?

### ISSUE THREAD

**Issue by Nazeh** [hypercore-protocol/corestore-next#5]
According to [hypercore-crypto](https://github.com/mafintosh/hypercore-crypto), version `^3.0.0` should be used instead of `^2.3.0` since this module targets `hypercore@^10.0.0`

**Comment by mafintosh** [comment]
That’s a bug. Send a PR. Only affects b4a

**Comment by Nazeh** [comment]
@mafintosh opened #6
